name: Authenticate with GitHub
description: Authenticates with GitHub using a provided token.

inputs:
  GITHUB_TOKEN:
    description: GitHub token for authentication.
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate with GitHub
      shell: pwsh
      run: |
        echo ${{ inputs.GITHUB_TOKEN }} | gh auth login --with-token